[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = [
  'wget',
  'gnupg',
  'ca-certificates',
  'fonts-liberation',
  'libasound2',
  'libatk-bridge2.0-0',
  'libatk1.0-0',
  'libatspi2.0-0',
  'libcups2',
  'libdbus-1-3',
  'libdrm2',
  'libgbm1',
  'libgtk-3-0',
  'libnspr4',
  'libnss3',
  'libwayland-client0',
  'libxcomposite1',
  'libxdamage1',
  'libxfixes3',
  'libxkbcommon0',
  'libxrandr2',
  'xdg-utils'
]

[phases.install]
cmds = [
  'wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb',
  'apt-get install -y ./google-chrome-stable_current_amd64.deb',
  'rm google-chrome-stable_current_amd64.deb',
  'npm install'
]

[start]
cmd = 'NODE_ENV=production node index.js'
