[phases.setup]
nixPkgs = ['nodejs_20', 'chromium']

[phases.install]
cmds = ['npm install']

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/var/nix/profiles/default/bin/chromium'

[start]
cmd = 'NODE_ENV=production node index.js'
